# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a73d07b62c61dda168dd63dcd993cd0e8e5f1030d596425ae2503d27e823f783b11eabe12b2f7541ddf233853c655d65e184aa184594ba1d403e676d904d9a1b

test:
  secret_key_base: b0d95ef4a55d4a7e5061f2d6e70cd4b01221e2f575c17d1cfdfc2c5c286fe9a8706a943e99d82714a8ea25d115262810bcf6bfaba1dc7f39df47f2f861693528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
